version: "2"

services:
  v2ray:
    container_name: v2ray
    image: "v2ray/official:latest"
    restart: unless-stopped
    volumes:
      - "./config.json:/etc/v2ray/config.json"

  nginx:
    container_name: nginx
    image: "nginx:alpine"
    restart: unless-stopped
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
